version: '3'
services:
  web:
    container_name: django
    #restart: unless-stopped
    build: ./app
    command: gunicorn sakkokassa.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - db:/home/app/web/DB
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
 
  nginx-proxy:
    container_name: nginx-proxy
    #restart: unless-stopped
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/staticfiles
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - web

  nginx-proxy-letsencrypt:
    container_name: letsencrypt
    #restart: unless-stopped
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  db:
  certs:
  html:
  vhost:
  acme: