# Generated by Django 3.2.5 on 2021-08-19 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelaaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sakko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvm', models.DateField(default=datetime.date(2021, 8, 19))),
                ('kerroin', models.PositiveSmallIntegerField(choices=[(1, 'x1'), (2, 'x2'), (3, 'x3'), (4, 'x4'), (5, 'x5')], max_length=1)),
                ('selite', models.CharField(max_length=100)),
                ('pelaaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pelaaja')),
                ('rike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rike')),
            ],
        ),
    ]
