# Generated by Django 3.2.5 on 2021-08-19 13:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sakko',
            name='kerroin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'x1'), (2, 'x2'), (3, 'x3'), (4, 'x4'), (5, 'x5')]),
        ),
        migrations.AlterField(
            model_name='sakko',
            name='pvm',
            field=models.DateField(default=datetime.datetime(2021, 8, 19, 13, 8, 38, 503475, tzinfo=utc)),
        ),
    ]
