# Generated by Django 3.2.5 on 2021-08-19 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210819_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sakko',
            name='pvm',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
