# Generated by Django 3.2.5 on 2021-08-19 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sakko_pvm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kulut',
            fields=[
                ('kulu_id', models.AutoField(primary_key=True, serialize=False)),
                ('kulu_pvm', models.DateField(default=django.utils.timezone.now)),
                ('kulu_selite', models.CharField(max_length=50)),
                ('kulu_summa', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelaajat',
            fields=[
                ('pelaaja_id', models.AutoField(primary_key=True, serialize=False)),
                ('pelaaja_nimi', models.CharField(max_length=15)),
                ('saadut_sakot', models.PositiveSmallIntegerField()),
                ('maksetut_sakot', models.PositiveSmallIntegerField()),
                ('jäljellä_sakot', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rikkeet',
            fields=[
                ('rike_id', models.AutoField(primary_key=True, serialize=False)),
                ('rike_kuvaus', models.CharField(max_length=50)),
                ('rike_summa', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='sakko',
            old_name='selite',
            new_name='sakko_selite',
        ),
        migrations.RemoveField(
            model_name='sakko',
            name='kerroin',
        ),
        migrations.RemoveField(
            model_name='sakko',
            name='pelaaja',
        ),
        migrations.AddField(
            model_name='sakko',
            name='sakko_summa',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sakko',
            name='tuplasakko',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='Pelaaja',
        ),
        migrations.AddField(
            model_name='sakko',
            name='sakko_pelaaja',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.pelaajat'),
        ),
        migrations.AlterField(
            model_name='sakko',
            name='rike',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.rikkeet'),
        ),
        migrations.DeleteModel(
            name='Rike',
        ),
    ]
