# Generated by Django 3.2.5 on 2021-09-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210819_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sakko',
            old_name='rike',
            new_name='rike_id',
        ),
        migrations.RenameField(
            model_name='sakko',
            old_name='sakko_pelaaja',
            new_name='sakotettu_pelaaja',
        ),
    ]
