# Generated by Django 3.2.5 on 2021-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210903_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelaajat',
            name='pelaaja_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
