# Generated by Django 3.2.5 on 2021-09-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_pelaajat_pelaaja_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelaajat',
            name='jäljellä_sakot',
        ),
    ]
