# Generated by Django 3.2.5 on 2021-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_pelaajat_jäljellä_sakot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelaajat',
            name='maksetut_sakot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pelaajat',
            name='saadut_sakot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
