# Generated by Django 3.2.5 on 2021-09-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210903_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sakko',
            old_name='sakotettu_pelaaja',
            new_name='sakotettu',
        ),
    ]
