# Generated by Django 3.2.5 on 2021-09-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_sakotettu_pelaaja_sakko_sakotettu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sakko',
            old_name='sakotettu',
            new_name='pelaaja_id',
        ),
    ]
