# Generated by Django 3.2.5 on 2021-11-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_sakotettu_sakko_pelaaja_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rikkeet',
            name='rike_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sakko',
            name='pvm',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sakko',
            name='sakko_summa',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
