# Generated by Django 3.2.5 on 2021-11-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_rikkeet_rike_summa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sakko',
            name='tuplasakko',
        ),
    ]
