# Generated by Django 3.2.5 on 2021-11-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_sakko_tuplasakko'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maksu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvm', models.DateField()),
                ('maksu_summa', models.PositiveSmallIntegerField()),
                ('pelaaja_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main.pelaajat')),
            ],
        ),
    ]
